// Code generated by protoc-gen-go.
// source: gpssvc.proto
// DO NOT EDIT!

/*
Package gpssvc is a generated protocol buffer package.

It is generated from these files:
	gpssvc.proto

It has these top-level messages:
	Position
*/
package gpssvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Position struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	// true track when available
	Heading float64 `protobuf:"fixed64,3,opt,name=heading" json:"heading,omitempty"`
	// speed in km/h, ground speed when available
	Speed float64 `protobuf:"fixed64,4,opt,name=speed" json:"speed,omitempty"`
	// approximating precisions in meters
	HorizontalPrecision float64                     `protobuf:"fixed64,5,opt,name=horizontal_precision,json=horizontalPrecision" json:"horizontal_precision,omitempty"`
	Ts                  *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=ts" json:"ts,omitempty"`
	// matched data
	Matched          bool    `protobuf:"varint,7,opt,name=matched" json:"matched,omitempty"`
	MatchedLatitude  float64 `protobuf:"fixed64,8,opt,name=matched_latitude,json=matchedLatitude" json:"matched_latitude,omitempty"`
	MatchedLongitude float64 `protobuf:"fixed64,9,opt,name=matched_longitude,json=matchedLongitude" json:"matched_longitude,omitempty"`
	MatchedHeading   float64 `protobuf:"fixed64,10,opt,name=matched_heading,json=matchedHeading" json:"matched_heading,omitempty"`
	MatchedDistance  float64 `protobuf:"fixed64,11,opt,name=matched_distance,json=matchedDistance" json:"matched_distance,omitempty"`
	RoadName         string  `protobuf:"bytes,12,opt,name=road_name,json=roadName" json:"road_name,omitempty"`
	Hint             string  `protobuf:"bytes,13,opt,name=hint" json:"hint,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Position) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Position) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Position) GetHeading() float64 {
	if m != nil {
		return m.Heading
	}
	return 0
}

func (m *Position) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Position) GetHorizontalPrecision() float64 {
	if m != nil {
		return m.HorizontalPrecision
	}
	return 0
}

func (m *Position) GetTs() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Position) GetMatched() bool {
	if m != nil {
		return m.Matched
	}
	return false
}

func (m *Position) GetMatchedLatitude() float64 {
	if m != nil {
		return m.MatchedLatitude
	}
	return 0
}

func (m *Position) GetMatchedLongitude() float64 {
	if m != nil {
		return m.MatchedLongitude
	}
	return 0
}

func (m *Position) GetMatchedHeading() float64 {
	if m != nil {
		return m.MatchedHeading
	}
	return 0
}

func (m *Position) GetMatchedDistance() float64 {
	if m != nil {
		return m.MatchedDistance
	}
	return 0
}

func (m *Position) GetRoadName() string {
	if m != nil {
		return m.RoadName
	}
	return ""
}

func (m *Position) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "Position")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GPSSVC service

type GPSSVCClient interface {
	// LivePosition streams Position updates
	LivePosition(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (GPSSVC_LivePositionClient, error)
	// InjectPosition Inject fake position
	// use it for debug purpose only
	InjectPosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type gPSSVCClient struct {
	cc *grpc.ClientConn
}

func NewGPSSVCClient(cc *grpc.ClientConn) GPSSVCClient {
	return &gPSSVCClient{cc}
}

func (c *gPSSVCClient) LivePosition(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (GPSSVC_LivePositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GPSSVC_serviceDesc.Streams[0], c.cc, "/GPSSVC/LivePosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &gPSSVCLivePositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GPSSVC_LivePositionClient interface {
	Recv() (*Position, error)
	grpc.ClientStream
}

type gPSSVCLivePositionClient struct {
	grpc.ClientStream
}

func (x *gPSSVCLivePositionClient) Recv() (*Position, error) {
	m := new(Position)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gPSSVCClient) InjectPosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/GPSSVC/InjectPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GPSSVC service

type GPSSVCServer interface {
	// LivePosition streams Position updates
	LivePosition(*google_protobuf.Empty, GPSSVC_LivePositionServer) error
	// InjectPosition Inject fake position
	// use it for debug purpose only
	InjectPosition(context.Context, *Position) (*google_protobuf.Empty, error)
}

func RegisterGPSSVCServer(s *grpc.Server, srv GPSSVCServer) {
	s.RegisterService(&_GPSSVC_serviceDesc, srv)
}

func _GPSSVC_LivePosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GPSSVCServer).LivePosition(m, &gPSSVCLivePositionServer{stream})
}

type GPSSVC_LivePositionServer interface {
	Send(*Position) error
	grpc.ServerStream
}

type gPSSVCLivePositionServer struct {
	grpc.ServerStream
}

func (x *gPSSVCLivePositionServer) Send(m *Position) error {
	return x.ServerStream.SendMsg(m)
}

func _GPSSVC_InjectPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Position)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPSSVCServer).InjectPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GPSSVC/InjectPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPSSVCServer).InjectPosition(ctx, req.(*Position))
	}
	return interceptor(ctx, in, info, handler)
}

var _GPSSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GPSSVC",
	HandlerType: (*GPSSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InjectPosition",
			Handler:    _GPSSVC_InjectPosition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LivePosition",
			Handler:       _GPSSVC_LivePosition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gpssvc.proto",
}

func init() { proto.RegisterFile("gpssvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdb, 0x6a, 0xdb, 0x30,
	0x18, 0xc6, 0x39, 0xda, 0x7f, 0xb2, 0x6c, 0xd3, 0xc2, 0x10, 0xce, 0x60, 0x66, 0x37, 0xf3, 0x36,
	0x70, 0xd6, 0xe4, 0x11, 0xda, 0xd2, 0x16, 0x42, 0x09, 0x4e, 0xe9, 0xad, 0x51, 0x6c, 0xd5, 0x56,
	0xb1, 0x25, 0x63, 0x29, 0x81, 0xf6, 0x11, 0xfb, 0x54, 0x25, 0xb2, 0xe5, 0xf4, 0x40, 0xef, 0xf4,
	0x1d, 0xf4, 0xfb, 0xff, 0x3e, 0x0b, 0xc6, 0x69, 0x29, 0xe5, 0x3e, 0x0e, 0xca, 0x4a, 0x28, 0xe1,
	0xce, 0x52, 0x21, 0xd2, 0x9c, 0xce, 0x35, 0xda, 0xee, 0xee, 0xe6, 0xb4, 0x28, 0xd5, 0x43, 0x23,
	0xfe, 0x7c, 0x2b, 0x2a, 0x56, 0x50, 0xa9, 0x48, 0x51, 0xd6, 0x86, 0x5f, 0x4f, 0x5d, 0xb0, 0xd7,
	0x42, 0x32, 0xc5, 0x04, 0x47, 0x2e, 0xd8, 0x39, 0x51, 0x4c, 0xed, 0x12, 0x8a, 0x2d, 0xcf, 0xf2,
	0xad, 0xb0, 0xc5, 0xe8, 0x07, 0x38, 0xb9, 0xe0, 0x69, 0x2d, 0x76, 0xb4, 0x78, 0x24, 0x10, 0x86,
	0x61, 0x46, 0x49, 0xc2, 0x78, 0x8a, 0xbb, 0x5a, 0x33, 0x10, 0x4d, 0xa1, 0x2f, 0x4b, 0x4a, 0x13,
	0xdc, 0xd3, 0x7c, 0x0d, 0xd0, 0x09, 0x4c, 0x33, 0x51, 0xb1, 0x47, 0xc1, 0x15, 0xc9, 0xa3, 0xb2,
	0xa2, 0x31, 0x93, 0x4c, 0x70, 0xdc, 0xd7, 0xa6, 0x6f, 0x47, 0x6d, 0x6d, 0x24, 0xf4, 0x17, 0x3a,
	0x4a, 0xe2, 0x81, 0x67, 0xf9, 0xa3, 0x85, 0x1b, 0xd4, 0xb9, 0x02, 0x93, 0x2b, 0xb8, 0x31, 0xb9,
	0xc2, 0x8e, 0x92, 0x87, 0x75, 0x0a, 0xa2, 0xe2, 0x8c, 0x26, 0x78, 0xe8, 0x59, 0xbe, 0x1d, 0x1a,
	0x88, 0xfe, 0xc0, 0x97, 0xe6, 0x18, 0xb5, 0x51, 0x6d, 0xfd, 0xd1, 0xcf, 0x0d, 0xbf, 0x32, 0x89,
	0xff, 0xc1, 0xd7, 0xd6, 0xda, 0x26, 0x77, 0xb4, 0xd7, 0xcc, 0x58, 0xb5, 0x05, 0xfc, 0x06, 0x73,
	0x3f, 0x32, 0x45, 0x80, 0xb6, 0x4e, 0x1a, 0xfa, 0xb2, 0xe9, 0xe3, 0xc5, 0x02, 0x09, 0x93, 0x8a,
	0xf0, 0x98, 0xe2, 0xd1, 0xab, 0x05, 0xce, 0x1a, 0x1a, 0xcd, 0xc0, 0xa9, 0x04, 0x49, 0x22, 0x4e,
	0x0a, 0x8a, 0xc7, 0x9e, 0xe5, 0x3b, 0xa1, 0x7d, 0x20, 0xae, 0x49, 0x41, 0x11, 0x82, 0x5e, 0xc6,
	0xb8, 0xc2, 0x9f, 0x34, 0xaf, 0xcf, 0x8b, 0x0a, 0x06, 0x17, 0xeb, 0xcd, 0xe6, 0xf6, 0x14, 0x2d,
	0x61, 0xbc, 0x62, 0x7b, 0xda, 0xfe, 0xd9, 0xef, 0xef, 0x0a, 0x3b, 0x3f, 0xbc, 0x12, 0xd7, 0x09,
	0x8c, 0xe5, 0xbf, 0x85, 0x96, 0x30, 0xb9, 0xe2, 0xf7, 0x34, 0x56, 0xed, 0xb5, 0xa3, 0xec, 0x7e,
	0x30, 0x61, 0x3b, 0xd0, 0x78, 0xf9, 0x1c, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x4c, 0xcd, 0xc6, 0x95,
	0x02, 0x00, 0x00,
}
